### ISSUE TITLE
iteration相關問題

### ISSUE THREAD

**Issue by che1007** [nie-lang/DeepRectangling#11]
你好，想詢問為何iteration數是自行設定的，而不是根據input data的數量及batch size的大小來得到有多少個iteration；另外也想詢問為何在train.py沒有看到設定epoch的值

**Comment by nie-lang** [comment]
这份代码中，我实际上并没有设定epoch的数量，只有iteration的数量。

**Comment by che1007** [comment]
不好意思，因為我剛開始入門deep learning可能觀念還不太正確，但就我目前的認知 iteration=input data(數量) / batch size，所以我才會對自行設定iteration數的部分有疑問，我的想法是只需要設置好batch size，還是說我的觀念有誤。

**Comment by nie-lang** [comment]
你所给的公式是一个epoch所需的迭代次数的计算公式。若要改变epoch的数量，无论是增加iteration数量或是增大batch size都是可以的。

我这份代码中只是没有明确设置epoch的数量，只用iteration来表示，实际上我觉得影响不大。不过按你所说设置epoch会使得代码更加规范

**Comment by che1007** [comment]
了解，謝謝你用心地回覆！

**Comment by che1007** [comment]
不好意思，再打擾一下，我最近有看你在github一連串關於image stitching的code及paper，想請問這份code是為了要解決在Unsupervised_Deep_Image_Stitching_Reconstructing_Stitched_Features_to_Images這份code運行產生拼接圖像後照片扭曲的問題嗎?

**Comment by nie-lang** [comment]
你说的扭曲是畸变吗？如果是畸变的话，不是解决这个问题

rectangling解决的是图像不规则的边界问题，在内容保真的前提下，将不规则形状变为规则矩形

**Comment by che1007** [comment]
了解，我上面描述的扭曲也指生成拼接圖像後的不規則邊界。
