### ISSUE TITLE
ground truth and mesh

### ISSUE THREAD

**Issue by che1007** [nie-lang/DeepRectangling#12]
你好
如果我以自己拍攝的兩張照片經由UnsupervisedDeepImageStitching完成拼接後，想藉由此份代碼來解決不規則邊界問題，輸入只有拼接完的圖，但缺少了gt 及mesh，這問題應該如何去解決

**Comment by nie-lang** [comment]
1. 这份代码的输入为拼接图和对应的mask，gt是用于训练的，测试阶段并不需要。mask可以由unsupervised stitching第一步alignment之后得到的mask1和mask2简单融合得到；或者采用阈值分割的方式，直接从拼接图得到mask

2. 另一种解决方式则是重新训练模型，需要修改代码，去掉mask输入及边界约束项。
